name: Build and Test
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: docker
    container:
      image: git.kalelzar.xyz/kalelzar/kwatcher-build:0.2-alpine-25.5
      credentials:
        username: ${{secrets.USER}}
        password: ${{secrets.TOKEN}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{secrets.FETCH_TOKEN}}
      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            .zig-cache
            ~/.cache/zig
          key: ${{ forge.repository }}-zig-${{ matrix.targets }}-${{ hashFiles('build.zig.zon') }}
          restore-keys: |
            ${{ forge.repository }}-zig-${{ matrix.targets }}-
      - name: Check
        run: zig build check --summary all
      - name: Test
        run: zig build test --summary all


